### ISSUE TITLE
Deprecation warning when you add the gem in your Gemfile in a Rails project

### ISSUE THREAD

**Issue by beauraF** [TankerHQ/identity-ruby#13]
Hello,

Requiring the gem in your `Gemfile` in a rails project with:

```ruby
gem 'tanker-identity', git: 'https://github.com/TankerHQ/identity-ruby'
```

Will necessarily trigger a deprecation warning message. Because `lib/tanker-identity.rb` is your entrypoint.

To avoid it you have to add it like this:

```ruby
gem 'tanker-identity', git: 'https://github.com/TankerHQ/identity-ruby', require: 'tanker/identity'
```

Do you have a plan, on how to remove it?

**Comment by maximerety** [comment]
Hi @beauraF,

Thank you for your report.

We recently decided to follow stricter naming conventions (as described on [rubygems.org](https://guides.rubygems.org/name-your-gem/)) and moved to the `require 'tanker/identity'` form.

Nevertheless, having to specify a `require:` argument in the Gemfile for Bundler to "auto-require" the gems is pretty annoying.

So, we decided to revert the deprecation warning and to keep the `require 'tanker-identity'` form as a valid alias.

Here's the pull request reverting the warning: https://github.com/TankerHQ/identity-ruby/pull/14

Would you be able to check if it's working for you with the following code?

```ruby
gem 'tanker-identity', git: 'https://github.com/TankerHQ/identity-ruby', ref: 'cc7c898'
```

Once the pull request merged, the `ref:` won't be necessary anymore.

**Comment by beauraF** [comment]
Hi @maximerety,

It works great.

I report this ""issue'' because I thought we could handle it with a gemspec entry. But after spending a little more time on it, seems we cannot: [link](https://bundler.io/gemfile.html#:~:text=If%20a%20gem's%20main%20file,specify%20how%20to%20require%20it.&text=Specify%20%3Arequire%20%3D%3E%20false%20to,install%20it%20and%20maintain%20dependencies.&text=In%20order%20to%20require%20gems,require%20in%20your%20application.).

So, actually, I don't have any worry about requiring it by myself. I'll let you decide that on your own. :D


Thanks for your quick answer.

**Comment by maximerety** [comment]
MR #14 has been merged to `master`.

Thank you @beauraF for your research and feedback.
